# Generated by Django 5.0.7 on 2024-07-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='total_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
