# Generated by Django 5.0.7 on 2024-07-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_theater_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='total_seats',
            field=models.IntegerField(default=0),
        ),
    ]
